#!/bin/bash

alias ll="ls -l"
alias mv="mv -i"
alias rm="rm -i"

alias   path='echo ${PATH}            | tr \: \\n'
alias  lpath='echo ${LIBRARY_PATH}    | tr \: \\n'
alias ldpath='echo ${LD_LIBRARY_PATH} | tr \: \\n'
alias  ppath='echo ${PYTHONPATH}      | tr \: \\n'

alias geany="geany &> /dev/null"

alias findlarge="find -type f -printf '%12s   %p\n'     | sort -n | tail -100"
alias  findlast="find -type f -printf '%T@   %t   %p\n' | sort -n | tail -100"
alias sa="sacct --allusers --format=JobID,Partition,NNodes,ReqCPUS,Account,User,JobName,Priority,NodeList,Start,End,Elapsed,State"
alias sq="squeue -l --format=\"%.6i %10P %.5D %.4C %12a %10u %48j %.8Q %.8y %.10M %.10l %10T %R\""
alias update="sudo bash -c 'apt update && apt upgrade && apt dist-upgrade && apt autoremove && apt clean'"
alias uz="unzip input.zip && find -type d -exec chmod 755 {} + && find -type f -exec chmod 644 {} + && chmod 755 *.sh"
alias    vpn_connect="/opt/paloaltonetworks/globalprotect/globalprotect connect    --portal engr-split.vpn.wisc.edu"
alias vpn_disconnect="/opt/paloaltonetworks/globalprotect/globalprotect disconnect --portal engr-split.vpn.wisc.edu"
