#!/bin/bash

export ARIES=lucas@10.0.12.5
export   TUX=ljjacobson@best-tux.cae.wisc.edu
export  CHTC=ljjacobson@submit2.chtc.wisc.edu
export  HPC1=ljjacobson@hpclogin1.chtc.wisc.edu
export  HPC2=ljjacobson@hpclogin2.chtc.wisc.edu
export   HPC=${HPC2}

alias aries="ssh -X ${ARIES}"
alias   tux="ssh -X ${TUX}"
alias  chtc="ssh -X ${CHTC}"
alias  hpc1="ssh -X ${HPC1}"
alias  hpc2="ssh -X ${HPC2}"
alias   hpc="ssh -X ${HPC}"
