#!/bin/bash

alias ls="ls --color=auto --group-directories-first"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll="ls -l"
alias mv="mv -i"
alias rm="rm -i"

alias path='echo ${PATH} | tr \: \\n'
alias lpath='echo ${LIBRARY_PATH} | tr \: \\n'
alias ldpath='echo ${LD_LIBRARY_PATH} | tr \: \\n'
alias ppath='echo ${PYTHONPATH} | tr \: \\n'

alias findlarge="find -type f -printf \"%s %p\n\" | sort -n"
alias sa="sacct --allusers --format=JobID,Partition,NNodes,ReqCPUS,Account,User,JobName,Priority,NodeList,Start,End,Elapsed,State"
alias sq="squeue -l --format=\"%.6i %10P %.5D %.4C %12a %10u %48j %.8Q %.8y %.10M %.10l %10T %R\""
alias update="sudo bash -c 'apt update && apt upgrade && apt dist-upgrade && apt autoremove && apt clean'"
alias uz="unzip input.zip && find -type f -exec chmod 644 {} + && chmod 755 *.sh"
alias vpn="/opt/paloaltonetworks/globalprotect/globalprotect connect --portal engr-split.vpn.wisc.edu"
