#!/bin/bash

export NO_AT_BRIDGE=1
export jobs=`grep -c processor /proc/cpuinfo`

test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
alias ls="ls --color=auto"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll="ls -l"
alias rm="rm -i"
alias mv="mv -i"

function parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
if [ "$color_prompt" = yes ]; then
  PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;31m\] $(parse_git_branch)\[\033[00m\]\$ '
else
  PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w$(parse_git_branch)\$ '
fi

export ACI1=ljjacobson@aci-service-1.chtc.wisc.edu
export ACI2=ljjacobson@aci-service-2.chtc.wisc.edu
export ACI=${ACI2}
export ARIES=lucas@192.168.240.10
export CONDOR=ljjacobson@submit-3.chtc.wisc.edu
export PHOENIX=${PHOENIX1}
export RAIKOU=lucas@192.168.240.73
export TUX=lucasj@best-tux.cae.wisc.edu
export TUXC1=lucasj@tux-c1.cae.wisc.edu
export TUXC2=lucasj@tux-c2.cae.wisc.edu
export TUXC3=lucasj@tux-c3.cae.wisc.edu
export ZAPDOS=lucas@zapdos.ep.wisc.edu

alias aci1="ssh -X ${ACI1}"
alias aci2="ssh -X ${ACI2}"
alias aci="ssh -X ${ACI}"
alias aries="ssh -X ${ARIES}"
alias condor="ssh -X ${CONDOR}"
alias phoenix="ssh -X ${PHOENIX}"
alias raikou="ssh -X ${RAIKOU}"
alias tux="ssh -X ${TUX}"
alias tuxc1="ssh -X ${TUXC1}"
alias tuxc2="ssh -X ${TUXC2}"
alias tuxc3="ssh -X ${TUXC3}"
alias zapdos="ssh -X ${ZAPDOS}"

function path() {
  echo ${PATH} | tr \: \\n
}
function ldpath() {
  echo ${LD_LIBRARY_PATH} | tr \: \\n
}
function ppath() {
  echo ${PYTHONPATH} | tr \: \\n
}
